//! @tags complexity
//! @citations Cousot05

//Generated by c2fsm -cut -nodiv -int 
model main {
var N,i,j;
//parameters N;
states stop,start,lbl_5_2,lbl_7_2;
transition t_25 :={
  from  := start;
  to    := stop;
  guard := (N <= 0);
  action:= i' = N;
};
transition t_26 :={
  from  := start;
  to    := lbl_5_2;
  guard := ( (1 <= N) && (1 <= j) );
  action:= i' = N, j' = j-1;
};
transition t_27 :={
  from  := start;
  to    := lbl_7_2;
  guard := ( (1 <= N) && (j <= 0) );
  action:= i' = N-1, j' = N;
};
transition t_19 :={
  from  := lbl_5_2;
  to    := stop;
  guard := (i <= 0);
  action:=;
};
transition t_20 :={
  from  := lbl_5_2;
  to    := lbl_5_2;
  guard := ( (1 <= i) && (1 <= j) );
  action:= j' = j-1;
};
transition t_21 :={
  from  := lbl_5_2;
  to    := lbl_7_2;
  guard := ( (1 <= i) && (j <= 0) );
  action:= i' = i-1, j' = N;
};
transition t_22 :={
  from  := lbl_7_2;
  to    := stop;
  guard := (i <= 0);
  action:=;
};
transition t_23 :={
  from  := lbl_7_2;
  to    := lbl_5_2;
  guard := ( (1 <= i) && (1 <= j) );
  action:= j' = j-1;
};
transition t_24 :={
  from  := lbl_7_2;
  to    := lbl_7_2;
  guard := ( (1 <= i) && (j <= 0) );
  action:= i' = i-1, j' = N;
};
}
strategy dumb {
    Region init := { state = start };
}

