//! @tags complexity
//! @citations ChawdharyCGSY08

//Generated by c2fsm -cut -nodiv -int 
model main {
var x,y,z;
//parameters z;
states stop,start,lbl_9_1,lbl_11_1;
transition t_22 :={
  from  := start;
  to    := lbl_9_1;
  guard := (0 = z);
  action:= x' = 1, y' = 100;
};
transition t_23 :={
  from  := start;
  to    := lbl_11_1;
  guard := ( (z+1 <= 0) || (1 <= z) );
  action:= x' = 2, y' = 100;
};
transition t_15 :={
  from  := lbl_9_1;
  to    := stop;
  guard := (40 <= x);
  action:=;
};
transition t_16 :={
  from  := lbl_9_1;
  to    := lbl_9_1;
  guard := ( (x <= 39) && (0 = z) );
  action:= x' = x+1;
};
transition t_17 :={
  from  := lbl_9_1;
  to    := lbl_11_1;
  guard := ( ( (x <= 39) && (z+1 <= 0) ) || ( (x <= 39) && (1 <= z) ) );
  action:= x' = x+2;
};
transition t_18 :={
  from  := lbl_11_1;
  to    := stop;
  guard := (40 <= x);
  action:=;
};
transition t_19 :={
  from  := lbl_11_1;
  to    := lbl_9_1;
  guard := ( (x <= 39) && (0 = z) );
  action:= x' = x+1;
};
transition t_20 :={
  from  := lbl_11_1;
  to    := lbl_11_1;
  guard := ( ( (x <= 39) && (z+1 <= 0) ) || ( (x <= 39) && (1 <= z) ) );
  action:= x' = x+2;
};
}
strategy dumb {
    Region init := { state = start };
}

