//! @tags complexity
//! @citations AliasDFG10

//Generated by c2fsm -cut -nodiv -int 
model main {
var i,j,length,tmp_1,value;
//parameters j,length;
states stop,start,lbl_4_3,lbl_3_1,lbl_1_3;
transition t_18 :={
  from  := start;
  to    := stop;
  guard := (length <= 1);
  action:= i' = 1;
};
transition t_19 :={
  from  := start;
  to    := lbl_3_1;
  guard := (2 <= length);
  action:= i' = 1, value' = ?;
};
transition t_20 :={
  from  := lbl_4_3;
  to    := lbl_4_3;
  guard := (0 <= j);
  action:= j' = j-1;
};
transition t_21 :={
  from  := lbl_4_3;
  to    := lbl_1_3;
  guard := true;
  action:= i' = i+1, tmp_1' = i;
};
transition t_22 :={
  from  := lbl_3_1;
  to    := lbl_4_3;
  guard := (1 <= i);
  action:= j' = i-2;
};
transition t_23 :={
  from  := lbl_3_1;
  to    := lbl_1_3;
  guard := true;
  action:= i' = i+1, j' = i-1, tmp_1' = i;
};
transition t_16 :={
  from  := lbl_1_3;
  to    := stop;
  guard := (length <= i);
  action:=;
};
transition t_17 :={
  from  := lbl_1_3;
  to    := lbl_3_1;
  guard := (i+1 <= length);
  action:= value' = ?;
};
}
strategy dumb {
    Region init := { state = start };
}

