//! @tags complexity
//! @citations ColonS02

//Generated by c2fsm -cut -nodiv -int 
model main {
var x,y1,y2,z;
//parameters x;
states stop,start,lbl_16_1,lbl_22_1,lbl_11_1;
transition t_49 :={
  from  := start;
  to    := stop;
  guard := (101 <= x);
  action:= y1' = x, y2' = 1, z' = x-10;
};
transition t_53 :={
  from  := start;
  to    := lbl_11_1;
  guard := (x <= 100);
  action:= y1' = x+11, y2' = 2;
};
transition t_54 :={
  from  := lbl_16_1;
  to    := stop;
  guard := (y2 <= 1);
  action:=;
};
transition t_55 :={
  from  := lbl_16_1;
  to    := lbl_16_1;
  guard := ( (111 <= y1) && (2 = y2) );
  action:= y1' = y1-10, y2' = y2-1, z' = y1-20;
};
transition t_56 :={
  from  := lbl_16_1;
  to    := lbl_22_1;
  guard := ( ( (y1 <= 110) && (3 <= y2) ) || ( (y1 <= 110) && (2 <= y2) ) );
  action:= y1' = y1+1, y2' = y2;
};
transition t_57 :={
  from  := lbl_16_1;
  to    := lbl_22_1;
  guard := ( (111 <= y1) && (3 <= y2) );
  action:= y1' = y1-9, y2' = y2-1;
};
transition t_58 :={
  from  := lbl_22_1;
  to    := stop;
  guard := (y2 <= 1);
  action:=;
};
transition t_59 :={
  from  := lbl_22_1;
  to    := lbl_16_1;
  guard := ( (111 <= y1) && (2 = y2) );
  action:= y1' = y1-10, y2' = y2-1, z' = y1-20;
};
transition t_60 :={
  from  := lbl_22_1;
  to    := lbl_22_1;
  guard := ( ( (y1 <= 110) && (3 <= y2) ) || ( (y1 <= 110) && (2 <= y2) ) );
  action:= y1' = y1+1, y2' = y2;
};
transition t_61 :={
  from  := lbl_22_1;
  to    := lbl_22_1;
  guard := ( (111 <= y1) && (3 <= y2) );
  action:= y1' = y1-9, y2' = y2-1;
};
transition t_51 :={
  from  := lbl_11_1;
  to    := lbl_11_1;
  guard := (y1 <= 100);
  action:= y1' = y1+11, y2' = y2+1;
};
transition t_62 :={
  from  := lbl_11_1;
  to    := stop;
  guard := ( (101 <= y1) && (y2 <= 1) );
  action:=;
};
transition t_63 :={
  from  := lbl_11_1;
  to    := lbl_16_1;
  guard := ( (111 <= y1) && (2 = y2) );
  action:= y1' = y1-10, y2' = y2-1, z' = y1-20;
};
transition t_64 :={
  from  := lbl_11_1;
  to    := lbl_22_1;
  guard := ( ( ( (y1 <= 110) && (101 <= y1) ) && (3 <= y2) ) || ( ( (y1 <= 110
) && (101 <= y1) ) && (2 <= y2) ) );
  action:= y1' = y1+1, y2' = y2;
};
transition t_65 :={
  from  := lbl_11_1;
  to    := lbl_22_1;
  guard := ( (111 <= y1) && (3 <= y2) );
  action:= y1' = y1-9, y2' = y2-1;
};
}
strategy dumb {
    Region init := { state = start };
}

