//! @tags complexity
//! @citations AliasDFG10

//Generated by c2fsm -cut -nodiv -int 
model main {
var i,n;
//parameters n;
states stop,start,lbl_3_2;
transition t_8 :={
  from  := start;
  to    := stop;
  guard := (i <= 1);
  action:=;
};
transition t_9 :={
  from  := start;
  to    := lbl_3_2;
  guard := (2 <= i);
  action:= i' = i-1;
};
transition t_6 :={
  from  := lbl_3_2;
  to    := stop;
  guard := (i <= 1);
  action:=;
};
transition t_7 :={
  from  := lbl_3_2;
  to    := lbl_3_2;
  guard := (2 <= i);
  action:= i' = i-1;
};
}
strategy dumb {
    Region init := { state = start };
}

