//! @tags complexity
//! @citations ChawdharyCGSY08

//Generated by c2fsm -cut -nodiv -int 
model main {
var a,mx,x;
//parameters mx;
states stop,start,lbl_10_1;
transition t_22 :={
  from  := start;
  to    := stop;
  guard := (mx <= 0);
  action:=;
};
transition t_30 :={
  from  := start;
  to    := lbl_10_1;
  guard := (1 <= mx);
  action:= a' = 1, x' = 2;
};
transition t_31 :={
  from  := start;
  to    := lbl_10_1;
  guard := (1 <= mx);
  action:= a' = -1, x' = 2;
};
transition t_26 :={
  from  := lbl_10_1;
  to    := stop;
  guard := (mx+1 <= x);
  action:=;
};
transition t_27 :={
  from  := lbl_10_1;
  to    := lbl_10_1;
  guard := (x <= mx);
  action:= a' = a+1, x' = x+1;
};
transition t_28 :={
  from  := lbl_10_1;
  to    := lbl_10_1;
  guard := (x <= mx);
  action:= a' = a-1, x' = x+1;
};
}
strategy dumb {
    Region init := { state = start };
}

