//! @tags complexity
//! @citations AliasDFG10

//Generated by c2fsm -cut -nodiv -int 
model main {
var array_size,i,j,mn,temp,tmp,tmp_1;
//parameters array_size;
states stop,start,lbl_9_1,lbl_5_3,lbl_1_3;
transition t_31 :={
  from  := start;
  to    := stop;
  guard := (array_size <= 1);
  action:= i' = 0;
};
transition t_40 :={
  from  := start;
  to    := lbl_5_3;
  guard := (2 <= array_size);
  action:= i' = 0, j' = 2, mn' = 0, tmp' = 1;
};
transition t_41 :={
  from  := start;
  to    := lbl_5_3;
  guard := (2 <= array_size);
  action:= i' = 0, j' = 2, mn' = 1, tmp' = 1;
};
transition t_24 :={
  from  := lbl_9_1;
  to    := lbl_1_3;
  guard := true;
  action:= i' = i+1, tmp_1' = i;
};
transition t_33 :={
  from  := lbl_5_3;
  to    := lbl_9_1;
  guard := (array_size <= j);
  action:= temp' = ?;
};
transition t_34 :={
  from  := lbl_5_3;
  to    := lbl_5_3;
  guard := (j+1 <= array_size);
  action:= j' = j+1, tmp' = j;
};
transition t_35 :={
  from  := lbl_5_3;
  to    := lbl_5_3;
  guard := (j+1 <= array_size);
  action:= j' = j+1, mn' = j, tmp' = j;
};
transition t_29 :={
  from  := lbl_1_3;
  to    := stop;
  guard := (array_size <= i+1);
  action:=;
};
transition t_37 :={
  from  := lbl_1_3;
  to    := lbl_5_3;
  guard := (i+2 <= array_size);
  action:= j' = i+2, mn' = i, tmp' = i+1;
};
transition t_38 :={
  from  := lbl_1_3;
  to    := lbl_5_3;
  guard := (i+2 <= array_size);
  action:= j' = i+2, mn' = i+1, tmp' = i+1;
};
}
strategy dumb {
    Region init := { state = start };
}

