//! @tags complexity
//! @citations AliasDFG10

//Generated by c2fsm -cut -nodiv -int 
model main {
var i,j,length,temp,test,tmp;
//parameters length;
states stop,start,lbl_7_1,lbl_5_3,lbl_1_3;
transition t_39 :={
  from  := start;
  to    := stop;
  guard := (length <= 1);
  action:= i' = length-1;
};
transition t_51 :={
  from  := start;
  to    := lbl_7_1;
  guard := (2 <= length);
  action:= i' = length-1, j' = 0, temp' = ?, test' = 0;
};
transition t_52 :={
  from  := start;
  to    := lbl_5_3;
  guard := (2 <= length);
  action:= i' = length-1, j' = 1, test' = 0, tmp' = 0;
};
transition t_35 :={
  from  := lbl_7_1;
  to    := lbl_5_3;
  guard := true;
  action:= j' = j+1, test' = 1, tmp' = j;
};
transition t_41 :={
  from  := lbl_5_3;
  to    := stop;
  guard := ( (i <= j) && (0 = test) );
  action:=;
};
transition t_42 :={
  from  := lbl_5_3;
  to    := lbl_1_3;
  guard := ( ( (i <= j) && (test+1 <= 0) ) || ( (i <= j) && (1 <= test) ) );
  action:= i' = i-1;
};
transition t_43 :={
  from  := lbl_5_3;
  to    := lbl_7_1;
  guard := (j+1 <= i);
  action:= temp' = ?;
};
transition t_44 :={
  from  := lbl_5_3;
  to    := lbl_5_3;
  guard := (j+1 <= i);
  action:= j' = j+1, tmp' = j;
};
transition t_37 :={
  from  := lbl_1_3;
  to    := stop;
  guard := (i <= 0);
  action:=;
};
transition t_47 :={
  from  := lbl_1_3;
  to    := lbl_7_1;
  guard := (1 <= i);
  action:= j' = 0, temp' = ?, test' = 0;
};
transition t_48 :={
  from  := lbl_1_3;
  to    := lbl_5_3;
  guard := (1 <= i);
  action:= j' = 1, test' = 0, tmp' = 0;
};
}
strategy dumb {
    Region init := { state = start };
}

