//! @tags complexity
//! @citations AliasDFG10

//Generated by c2fsm -cut -nodiv -int 
model main {
var array_size,i,increment,j,temp,tmp,tmp_1,tmp_2;
//parameters array_size;
states stop,start,lbl_12_1,lbl_12_3,lbl_10_1,lbl_7_1,lbl_5_3,lbl_2_1;
transition t_7 :={
  from  := start;
  to    := lbl_2_1;
  guard := true;
  action:= tmp_2' = ?;
};
transition t_16 :={
  from  := lbl_12_1;
  to    := lbl_12_3;
  guard := ( (increment <= 2tmp+1) && (2tmp <= increment) );
  action:= increment' = tmp;
};
transition t_26 :={
  from  := lbl_12_3;
  to    := stop;
  guard := (increment <= 0);
  action:=;
};
transition t_36 :={
  from  := lbl_12_3;
  to    := lbl_12_1;
  guard := ( (array_size <= 0) && (1 <= increment) );
  action:= i' = 0, tmp' = ?;
};
transition t_37 :={
  from  := lbl_12_3;
  to    := lbl_7_1;
  guard := ( (1 <= array_size) && (1 <= increment) );
  action:= i' = 0, j' = 0, temp' = ?;
};
transition t_30 :={
  from  := lbl_10_1;
  to    := lbl_10_1;
  guard := (increment <= j);
  action:= j' = j-increment;
};
transition t_31 :={
  from  := lbl_10_1;
  to    := lbl_5_3;
  guard := true;
  action:= i' = i+1, tmp_1' = i;
};
transition t_32 :={
  from  := lbl_7_1;
  to    := lbl_10_1;
  guard := (increment <= j);
  action:= j' = j-increment;
};
transition t_33 :={
  from  := lbl_7_1;
  to    := lbl_5_3;
  guard := true;
  action:= i' = i+1, tmp_1' = i;
};
transition t_34 :={
  from  := lbl_5_3;
  to    := lbl_12_1;
  guard := (array_size <= i);
  action:= tmp' = ?;
};
transition t_35 :={
  from  := lbl_5_3;
  to    := lbl_7_1;
  guard := (i+1 <= array_size);
  action:= j' = i, temp' = ?;
};
transition t_28 :={
  from  := lbl_2_1;
  to    := stop;
  guard := ( ( (array_size <= 2tmp_2+1) && (2tmp_2 <= array_size) ) && (tmp_2
 <= 0) );
  action:= increment' = tmp_2;
};
transition t_39 :={
  from  := lbl_2_1;
  to    := lbl_7_1;
  guard := ( ( (array_size <= 2tmp_2+1) && (2tmp_2 <= array_size) ) && (1 <= 
tmp_2) );
  action:= i' = 0, increment' = tmp_2, j' = 0, temp' = ?;
};
}
strategy dumb {
    Region init := { state = start };
}

