//! @tags complexity
//! @citations AliasDFG10

//Generated by c2fsm -cut -nodiv -int 
model relation1 {
var x,y;
//parameters;
states stop,start,lbl_4_1;
transition t_22 :={
  from  := start;
  to    := lbl_4_1;
  guard := true;
  action:= x' = ?;
};
transition t_18 :={
  from  := lbl_4_1;
  to    := stop;
  guard := true;
  action:= y' = x;
};
}
strategy dumb {
    Region init := { state = start };
}

