//! @tags complexity
//! @citations AliasDFG10

//Generated by c2fsm -cut -nodiv -int 
model main {
var da,db,r,temp;
//parameters r;
states stop,start,lbl_8_2,lbl_12_1;
transition t_28 :={
  from  := start;
  to    := stop;
  guard := (r+1 <= 0);
  action:=;
};
transition t_38 :={
  from  := start;
  to    := lbl_8_2;
  guard := (0 <= r);
  action:= da' = 2r-1, db' = 2r;
};
transition t_39 :={
  from  := start;
  to    := lbl_12_1;
  guard := (0 <= r);
  action:= da' = 2r-1, db' = 2r-1, temp' = 2r;
};
transition t_31 :={
  from  := lbl_8_2;
  to    := stop;
  guard := (da+1 <= r);
  action:=;
};
transition t_32 :={
  from  := lbl_8_2;
  to    := lbl_8_2;
  guard := (r <= da);
  action:= da' = da-1;
};
transition t_33 :={
  from  := lbl_8_2;
  to    := lbl_12_1;
  guard := (r <= da);
  action:= da' = db-1, db' = db-1, temp' = da;
};
transition t_34 :={
  from  := lbl_12_1;
  to    := stop;
  guard := (da+1 <= r);
  action:=;
};
transition t_35 :={
  from  := lbl_12_1;
  to    := lbl_8_2;
  guard := (r <= da);
  action:= da' = da-1;
};
transition t_36 :={
  from  := lbl_12_1;
  to    := lbl_12_1;
  guard := (r <= da);
  action:= da' = db-1, db' = db-1, temp' = da;
};
}
strategy dumb {
    Region init := { state = start };
}

