//! @tags complexity
//! @citations AliasDFG10

//Generated by c2fsm -cut -nodiv -int 
model main {
var i,j,tmp,tmp_1;
//parameters;
states stop,start,lbl_9_2,lbl_8_2;
transition t_15 :={
  from  := start;
  to    := stop;
  guard := (5 <= i);
  action:=;
};
transition t_21 :={
  from  := start;
  to    := lbl_9_2;
  guard := (i <= 2);
  action:= i' = i+1, j' = 0, tmp' = i;
};
transition t_22 :={
  from  := start;
  to    := lbl_8_2;
  guard := ( (i <= 4) && (3 <= i) );
  action:= j' = 1, tmp_1' = 0;
};
transition t_13 :={
  from  := lbl_9_2;
  to    := stop;
  guard := (5 <= i);
  action:=;
};
transition t_19 :={
  from  := lbl_9_2;
  to    := lbl_9_2;
  guard := (i <= 2);
  action:= i' = i+1, j' = 0, tmp' = i;
};
transition t_20 :={
  from  := lbl_9_2;
  to    := lbl_8_2;
  guard := ( (i <= 4) && (3 <= i) );
  action:= j' = 1, tmp_1' = 0;
};
transition t_17 :={
  from  := lbl_8_2;
  to    := lbl_9_2;
  guard := ( (i <= 2) || (10 <= j) );
  action:= i' = i+1, tmp' = i;
};
transition t_18 :={
  from  := lbl_8_2;
  to    := lbl_8_2;
  guard := ( (3 <= i) && (j <= 9) );
  action:= j' = j+1, tmp_1' = j;
};
}
strategy dumb {
    Region init := { state = start };
}

