//! @tags complexity
//! @citations AliasDFG10

//Generated by c2fsm -cut -nodiv -int 
model main {
var N,i,j;
//parameters N;
states stop,start,lbl_7_2,lbl_6_2;
transition t_18 :={
  from  := start;
  to    := stop;
  guard := (N <= 0);
  action:= i' = N;
};
transition t_25 :={
  from  := start;
  to    := lbl_6_2;
  guard := (1 <= N);
  action:= i' = N, j' = N-1;
};
transition t_16 :={
  from  := lbl_7_2;
  to    := stop;
  guard := (i <= 0);
  action:=;
};
transition t_22 :={
  from  := lbl_7_2;
  to    := lbl_7_2;
  guard := ( (N <= 0) && (1 <= i) );
  action:= i' = i-1, j' = N;
};
transition t_23 :={
  from  := lbl_7_2;
  to    := lbl_6_2;
  guard := ( (1 <= N) && (1 <= i) );
  action:= j' = N-1;
};
transition t_20 :={
  from  := lbl_6_2;
  to    := lbl_7_2;
  guard := (j <= 0);
  action:= i' = i-1;
};
transition t_21 :={
  from  := lbl_6_2;
  to    := lbl_6_2;
  guard := (1 <= j);
  action:= j' = j-1;
};
}
strategy dumb {
    Region init := { state = start };
}

