//! @tags complexity
//! @citations AliasDFG10

//Generated by c2fsm -cut -nodiv -int 
model main {
var x,y;
//parameters;
states stop,start,lbl_8_1,lbl_9_1;
transition t_13 :={
  from  := start;
  to    := stop;
  guard := ( (x+1 <= 0) || (y+1 <= 0) );
  action:=;
};
transition t_23 :={
  from  := start;
  to    := stop;
  guard := ( ( ( (x <= y+2) && (0 <= x) ) && (y <= x+2) ) && (0 <= y) );
  action:=;
};
transition t_24 :={
  from  := start;
  to    := lbl_8_1;
  guard := ( (x+3 <= y) && (0 <= x) );
  action:= x' = x+1;
};
transition t_25 :={
  from  := start;
  to    := lbl_9_1;
  guard := ( (y+3 <= x) && (0 <= y) );
  action:= y' = y+1;
};
transition t_17 :={
  from  := lbl_8_1;
  to    := stop;
  guard := ( (x <= y+2) && (y <= x+2) );
  action:=;
};
transition t_18 :={
  from  := lbl_8_1;
  to    := lbl_8_1;
  guard := (x+3 <= y);
  action:= x' = x+1;
};
transition t_19 :={
  from  := lbl_8_1;
  to    := lbl_9_1;
  guard := (y+3 <= x);
  action:= y' = y+1;
};
transition t_20 :={
  from  := lbl_9_1;
  to    := stop;
  guard := ( (x <= y+2) && (y <= x+2) );
  action:=;
};
transition t_21 :={
  from  := lbl_9_1;
  to    := lbl_8_1;
  guard := (x+3 <= y);
  action:= x' = x+1;
};
transition t_22 :={
  from  := lbl_9_1;
  to    := lbl_9_1;
  guard := (y+3 <= x);
  action:= y' = y+1;
};
}
strategy dumb {
    Region init := { state = start };
}

