/**
 * Copyright 2013 Gianluca Amato
 *
 * This file is part of JANDOM: JVM-based Analyzer for Numerical DOMains
 * JANDOM is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * JANDOM is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty ofa
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with JANDOM.  If not, see <http://www.gnu.org/licenses/>.
 */

package it.unich.sci.jandom.targets.jvm

import org.objectweb.asm.tree._
import soot.baf.Inst

/**
 * This exception is generated by the bytecode analyzers when an unknown opcode is
 * encountered.
 * @author Gianluca Amato <gamato@unich.it>
 */
abstract class UnsupportedByteCodeException(msg: String) extends Exception(msg)

/**
 * This exception is generated by the ASM analyzer when an unknown opcode is
 * encountered.
 * @param node the ASM instruction which has generated the fault
 * @author Gianluca Amato <gamato@unich.it>
 *
 */
case class UnsupportedASMByteCodeException(val node: AbstractInsnNode) extends UnsupportedByteCodeException("Unsupported ASM bytecode exception")

/**
 * This exception is generated by the Baf analyzer when an unknown opcode is
 * encountered.
 * @param node the instruction which has generated the fault
 * @author Gianluca Amato <gamato@unich.it>
 *
 */
case class UnsupportedBafByteCodeException(val inst: Inst) extends UnsupportedByteCodeException("Unsupported Baf bytecode exception")
